### ISSUE TITLE
F5 Refresh fails

### ISSUE THREAD

**Issue by chapati** [BeamMW/plugin-gallery#28]
1. Load headless wallet
2. Hit F5

Reload fails. Wallet is hung forever.
In jscript console 'Node connection reset' message is displayed.
This bug is clearly reproduced on linux Chrome 95.0.4638.54

This is not a bug in web wallet but in chrome itself. Reporded to chrome dev team here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1269096

**Comment by chapati** [comment]
Temporary fix is applied in web wallet to overcome chrome limitations.
Please check that this is not reproduced.

**Comment by Sergei-Beam** [comment]
checked
