### ISSUE TITLE
Headless -> Headed switch

### ISSUE THREAD

**Issue by chapati** [BeamMW/plugin-gallery#30]
When user triggers any action that requires web wallet or hits the 'connect to wallet' button connection sequence should start.

1) The following dialog should be displayed

![gnome-shell-screenshot-HALFD1](https://user-images.githubusercontent.com/12074933/142685737-56202442-d32c-482b-80ce-d3adfd459a2d.png)
d

2)  After user approves wallet connection gallery should switch to the normal mode, i.e. display all tabs, allow to buy/sell & display show my key button &c.

**Comment by Sergei-Beam** [comment]
checked
